- .github/workflows/ci.yml
- .mvn/extensions.xml
- README.md
- pom.xml
- releng/org.openhwgroup.corev.ide.cdt.aggregator/pom.xml
- releng/org.openhwgroup.corev.ide.cdt.parent/pom.xml
Add minimal Maven 3.6.3 + Tycho 1.7.0 build to setup the pipeline
> #2 Setup GutHub Actions for pipeline

- features/org.openhwgroup.corev.ide.feature/.project
- features/org.openhwgroup.corev.ide.feature/build.properties
- features/org.openhwgroup.corev.ide.feature/feature.properties
- features/org.openhwgroup.corev.ide.feature/feature.xml
- features/pom.xml
- releng/org.openhwgroup.corev.ide.aggregator/.project
- releng/org.openhwgroup.corev.ide.aggregator/pom.xml
- releng/org.openhwgroup.corev.ide.parent/pom.xml
- releng/org.openhwgroup.corev.ide.repository/.project
- releng/org.openhwgroup.corev.ide.repository/category.xml
- releng/org.openhwgroup.corev.ide.repository/pom.xml
- releng/org.openhwgroup.corev.ide.target/.project
- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
- releng/org.openhwgroup.corev.ide.target/pom.xml
Add manifests for org.openhwgroup.corev.ide.feature
> #6 Provide installable feature to be reused for downstream solutions

- README.md
> Add "Building" section to readme

- products/org.openhwgroup.corev.ide.product/org.openhwgroup.corev.ide.product.product
- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
Add Embedded CDT features to the target and .product
> #17 Eclipse Embedded CDT Integration

- bundles/org.openhwgroup.corev.ide.debug.ui/.classpath
- bundles/org.openhwgroup.corev.ide.debug.ui/.project
- bundles/org.openhwgroup.corev.ide.debug.ui/.settings/org.eclipse.jdt.core.prefs
- bundles/org.openhwgroup.corev.ide.debug.ui/META-INF/MANIFEST.MF
- bundles/org.openhwgroup.corev.ide.debug.ui/OSGI-INF/l10n/bundle.properties
- bundles/org.openhwgroup.corev.ide.debug.ui/build.properties
- features/org.openhwgroup.corev.ide.cdt.feature/feature.xml
- releng/org.openhwgroup.corev.ide.aggregator/pom.xml
Add "org.openhwgroup.corev.ide.debug.ui" bundle
> #19 OpenOCD for CORE-V integration

- products/org.openhwgroup.corev.ide.product/org.openhwgroup.corev.ide.product.product
Removed Jlink,Jumper,pyocd,sifive debuggers
Signed-off-by:Promodkumar CM <promod.kumar@ashling.com>
> Removed needless debuggers from the initial release

- .github/workflows/ci.yml
- releng/org.openhwgroup.corev.ide.parent/pom.xml
> #28 Produce Linux executables during the build

- bundles/org.openhwgroup.corev.ide/plugin.xml
> Fix license header for plugin.xml

- bundles/org.openhwgroup.corev.ide.debug.ui/about.html
- bundles/org.openhwgroup.corev.ide.debug.ui/build.properties
- bundles/org.openhwgroup.corev.ide.toolchain.gnu/about.html
- bundles/org.openhwgroup.corev.ide.toolchain.gnu/build.properties
- bundles/org.openhwgroup.corev.ide/about.html
- bundles/org.openhwgroup.corev.ide/build.properties
Added about.html to all the existing bundles
> #37 Add about.html to bundles to conform with EPL2.0

- bundles/org.openhwgroup.corev.ide.toolchain.gnu.core/META-INF/MANIFEST.MF
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.core/OSGI-INF/l10n/bundle.properties
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.core/build.properties
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.core/plugin.xml
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.core/templates/projects/HelloWorld_C_Project/template.properties
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.core/templates/projects/HelloWorld_C_Project/template.xml
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.ui/META-INF/MANIFEST.MF
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.ui/build.properties
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.ui/plugin.xml
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.ui/src/org/openhwgroup/corev/ide/internal/toolchain/gnu/ui/wizards/GnuToolchainOperation.java
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.ui/src/org/openhwgroup/corev/ide/internal/toolchain/gnu/ui/wizards/GnuToolchainWizardPage.java
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.ui/src/org/openhwgroup/corev/ide/internal/toolchain/gnu/ui/wizards/Messages.java
- bundles/org.openhwgroup.corev.ide.toolchain.gnu.ui/src/org/openhwgroup/corev/ide/internal/toolchain/gnu/ui/wizards/messages.properties
Add basic toolchain contributions
> #18 Integrate CORE-V GNU-based toolchain (by Embecosm)

- products/org.openhwgroup.corev.ide.product/.project
- products/org.openhwgroup.corev.ide.product/.settings/org.eclipse.core.resources.prefs
- products/org.openhwgroup.corev.ide.product/.settings/org.eclipse.m2e.core.prefs
- products/org.openhwgroup.corev.ide.product/pom.xml
- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
Switch to the latest bits of 2020-06
> #44 Catch up the train of SimRel 2020-12

- bundles/org.openhwgroup.corev.ide.ui.intro/.classpath
- bundles/org.openhwgroup.corev.ide.ui.intro/.project
- bundles/org.openhwgroup.corev.ide.ui.intro/.settings/org.eclipse.jdt.core.prefs
- bundles/org.openhwgroup.corev.ide.ui.intro/META-INF/MANIFEST.MF
- bundles/org.openhwgroup.corev.ide.ui.intro/OSGI-INF/l10n/bundle.properties
- bundles/org.openhwgroup.corev.ide.ui.intro/about.html
- bundles/org.openhwgroup.corev.ide.ui.intro/build.properties
- bundles/org.openhwgroup.corev.ide.ui.intro/plugin.xml
- bundles/org.openhwgroup.corev.ide/plugin.xml
- bundles/org.openhwgroup.corev.ide/plugin_customization.ini
- features/org.openhwgroup.corev.ide.feature/feature.xml
- releng/org.openhwgroup.corev.ide.aggregator/pom.xml
Created and integrated simple universal intro bundle.
Signed-off-by: Nikifor Fedorov <zelenyhleb@gmail.com>
> #49 Implement Intro page

- bundles/org.openhwgroup.corev.ide.ui.workbench/.classpath
- bundles/org.openhwgroup.corev.ide.ui.workbench/.project
- bundles/org.openhwgroup.corev.ide.ui.workbench/.settings/org.eclipse.jdt.core.prefs
- bundles/org.openhwgroup.corev.ide.ui.workbench/META-INF/MANIFEST.MF
- bundles/org.openhwgroup.corev.ide.ui.workbench/OSGI-INF/l10n/bundle.properties
- bundles/org.openhwgroup.corev.ide.ui.workbench/about.html
- bundles/org.openhwgroup.corev.ide.ui.workbench/build.properties
- bundles/org.openhwgroup.corev.ide.ui.workbench/plugin.xml
Create bundle
Signed-off-by: Nikifor Fedorov <zelenyhleb@gmail.com>
> #53 Add hardware selection wizard

- bundles/org.openhwgroup.corev.ide.ui.workbench/META-INF/MANIFEST.MF
- bundles/org.openhwgroup.corev.ide.ui.workbench/OSGI-INF/l10n/bundle.properties
- bundles/org.openhwgroup.corev.ide.ui.workbench/plugin.xml
- bundles/org.openhwgroup.corev.ide.ui.workbench/src/org/openhwgroup/corev/ide/ui/workbench/CoreVPerspective.java
- bundles/org.openhwgroup.corev.ide/plugin_customization.ini
- features/org.openhwgroup.corev.ide.feature/feature.xml
- releng/org.openhwgroup.corev.ide.aggregator/pom.xml
Added simple CORE-V Perspective
Signed-off-by: Nikifor Fedorov <zelenyhleb@gmail.com>
> #58 Add Core-V development perspective

- bundles/org.openhwgroup.corev.ide.ui.intro/META-INF/MANIFEST.MF
- bundles/org.openhwgroup.corev.ide.ui.intro/content/root.xhtml
- bundles/org.openhwgroup.corev.ide.ui.intro/src/org/openhwgroup/corev/ide/ui/intro/ShowHelpAction.java
- features/org.openhwgroup.corev.ide.feature/feature.xml
- releng/org.openhwgroup.corev.ide.aggregator/pom.xml
Added bundles to aggregator, added intro menu entry
Signed-off-by: Nikifor Fedorov <zelenyhleb@gmail.com>
> #62 Create some help content

- .github/workflows/ci.yml
- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
All the required work to use Eclipse SimRel 2021-03 as a target
> Switch to Eclipse SimRel 2021-03

- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
> Jetty is needed for integration with PlatfromIO

- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
Platform 4.20 (intermediate)
CDT 10.3
Orbit R20210602031627
> Switch to SimRel 2021-06 #76

- .mvn/extensions.xml
- releng/org.openhwgroup.corev.ide.parent/pom.xml
> Switch to Tycho 2.3.0 #78

- README.md
Update Java prerequisites to Java 11+
> Migrate to Java 11 #60

- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
Orbit switched to R20210825222808
Platform switched to 4.21
CDT switched to 10.3.3 (waiting for 10.4)
> #82 Switch to SimRel 2021-09

- .github/workflows/ci.yml
- bundles/org.openhwgroup.corev.ide/OSGI-INF/l10n/bundle.properties
- bundles/org.openhwgroup.corev.ide/about.mappings
- bundles/org.openhwgroup.corev.ide/about.properties
- releng/org.openhwgroup.corev.ide.parent/pom.xml
Fix manifests to consider build info
> About dialog should show build version #85

- products/org.openhwgroup.corev.ide.product/org.openhwgroup.corev.ide.product.product
- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
> Include Eclipse Passage #87

- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
Eclipse Platform 4.22
Eclipse EMF 2.28
Eclipse Passage 2.2.1
Eclipse CDT 10.5
Eclipse Orbit: special one, to fix log4j
> Update target to SimRel 2021-12 #93

- .github/workflows/ci.yml
- .mvn/extensions.xml
- README.md
- bundles/pom.xml
- features/pom.xml
- pom.xml
- products/org.openhwgroup.corev.ide.product/org.openhwgroup.corev.ide.product.product
- products/org.openhwgroup.corev.ide.product/pom.xml
- releng/org.openhwgroup.corev.ide.aggregator/pom.xml
- releng/org.openhwgroup.corev.ide.parent/pom.xml
- releng/org.openhwgroup.corev.ide.repository/category.xml
- releng/org.openhwgroup.corev.ide.repository/pom.xml
- releng/org.openhwgroup.corev.ide.target/org.openhwgroup.corev.ide.target.target
- releng/org.openhwgroup.corev.ide.target/pom.xml
> Prepare releng for 0.2.0 version #84
